### ISSUE TITLE
markdown-checklist and reference ids

### ISSUE THREAD

**Issue by bitbybit** [jandecaluwe/urubu#10]
Hi

When trying to build with markdown-checklist then I get following errors:
```
/usr/lib/python2.7/site-packages/urubu/md_extensions.py:90: UrubuWarning: Undefined ref [ ] in file './index.md'
  warn(undef_ref_warning.format(ref, this['fn']), UrubuWarning)
/usr/lib/python2.7/site-packages/urubu/md_extensions.py:90: UrubuWarning: Undefined ref [x] in file './index.md'
  warn(undef_ref_warning.format(ref, this['fn']), UrubuWarning)
```

```
* [ ] a task list item
* [ ] list syntax required
* [ ] normal **formatting**, @mentions, #1234 refs
* [ ] incomplete
* [x] completed
```

Also I get similar errors when links contain square brackets. For example:
```
[XDA Forum: [KERNEL][NEO/V] LuPuS GBv2 [STOCK GB][LINARO 4.7.3] 20-06-13](http://forum.xda-developers.com/showthread.php?t=2295074)
```

**Comment by jandecaluwe** [comment]
1) I consider taking out the checklist extension, should solve the issue
2) special symbols such as [ or ] can be escaped with \
3) UnicodeEncodeError's seem to be an issue with the stdlib warning module. PRs that solve this will be accepted.

**Comment by bitbybit** [comment]
1) Ok. I don't use checklists anymore.
2) Thanks for information.
3) This error suddenly gone away on my Arch Linux.

**Comment by jandecaluwe** [comment]
checklist extension taken out
