### ISSUE TITLE
Logo in browser tab

### ISSUE THREAD

**Issue by josyb** [jandecaluwe/urubu#20]
Chris (Felton) and I added a browser-tab logo for the MyHDL site. I suppose this would be an maintenance for all urubu users.
I added the <link> in the _base.html but I guess there must be a better way to do this?
A side question: how can I 'promote' an issue to 'enhancement' (or other label)?

**Comment by jandecaluwe** [comment]
@josyb Urubu expects templates (layouts) in the `_layout` directory - that is all. How you organize them and what content you put in them is completely up to the user. 

It is logical to add general features such as a browser-tap logo to the "base" template from which other templates inherit. I have named that `_base.html` for the sites I maintain (including Urubu's documentation site) but that is just my choice.
