### ISSUE TITLE
Adding search

### ISSUE THREAD

**Issue by xHN35RQ** [jandecaluwe/urubu#28]
Hello, I'm impressed with Urubu, thank you for making it. :trophy: 

I'm interested in adding a search feature to Urubu, do you have any suggestions the best way to go about that? I'm assuming a Javascript client-side search will probably be the only option.

**Comment by jandecaluwe** [comment]
I would probably into similar projects to find what can be borrowed :-) Yes, some Javascript client-search mechanism would be nice. For example, that works fine to render mathematical formulas, and all it took was loading a javascript library from a cdn in the base template file. http://www.jandecaluwe.com/blog/urubu-formulas.html

**Comment by xHN35RQ** [comment]
I'll look around and do some experimentation. Perhaps even submit a pull request. Thanks!

**Comment by xHN35RQ** [comment]
[Pykwiki](https://github.com/nullism/pykwiki/blob/master/source/about-search.md) creates a json search index at build time, and then uses javascript to access that. Is this portable to Urubu?

Perhaps Urubu could generate a LevelDB search database, and then queryi against it with something like [search-index](https://github.com/fergiemcdowall/search-index)?

**Comment by philippefaes** [comment]
We are using Google Custom search on our documentation site: http://doc.sigasi.com/manual/
Source at https://github.com/sigasi/sigasi_doc

**Comment by jandecaluwe** [comment]
Yes, why not ;-) Is it expensive to have the non-branded version?

**Comment by xHN35RQ** [comment]
Google custom search is definitely an option. At the moment I'm working on some projects that require local search, or somehow inaccessible from Google custom search.

**Comment by philippefaes** [comment]
@jandecaluwe If I remember correctly, they charge about 100$ per year.

**Comment by xHN35RQ** [comment]
Closing since it's not specifically an urubu issue.

**Comment by jandecaluwe** [comment]
Integrated Tipue Search in development. Please review http://urubu.jandecaluwe.com/manual/search.html

**Comment by xHN35RQ** [comment]
Brilliant. This looks very well done. Thank you!

Do you plan to eventually include Tipue Search and also `<main>` tags in the layouts in the Urubu Quickstart?

**Comment by jandecaluwe** [comment]
Yes, when this is officially released. I first want to be sure that we get the `<main>` tag to work with IE11.

**Comment by xHN35RQ** [comment]
It's not supported at all in IE at the moment. See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main#Browser_compatibility

Also: http://stackoverflow.com/a/26207036 and http://stackoverflow.com/q/26207016

Another option is to use something like [Normalize.css](https://necolas.github.io/normalize.css/) which includes this and other fixes to bring consistency to the various browsers.

**Comment by jandecaluwe** [comment]
I managed to check it in IE11 and saw no issues. Apparently the bootstrap template already contains `html5shiv.js`, which solves the issues.

**Comment by xHN35RQ** [comment]
Nice. :+1:

**Comment by xHN35RQ** [comment]
I just tested the Urubu quickstart and the search is working great. Thank you again @jandecaluwe you made my work easier. I'd rather not use Google Custom Search for any of the projects I'm working on.

**Comment by xHN35RQ** [comment]
So I'm guessing this issue can be closed?

**Comment by jandecaluwe** [comment]
Addressed in 0.9.0.
