### ISSUE TITLE
What is the recommended way to add a README.md to an Urubu project

### ISSUE THREAD

**Issue by heeckhau** [jandecaluwe/urubu#29]
I have created an Urubu project that I host on GitHub. On GitHub is is recommended to have a README.md in the root folder of a project. However, when I add this file, Urubu warns me that this file does not have a yaml frontmatter.

```
/usr/lib/python2.7/site-packages/urubu/readers.py:35: UrubuWarning: No yaml frontmatter found in ./README.md
  warnings.warn(yamlfm_warning.format(fn), UrubuWarning)
/usr/lib/python2.7/site-packages/urubu/project.py:176: UrubuWarning: No yaml front matter in './README.md' - ignored
  warn(yamlfm_warning.format(relfn), UrubuWarning)
````

What is the recommended way to deal with this?

**Comment by jandecaluwe** [comment]
You could add the yaml frontmatter if it is OK to have it in the build. As it is compatible with jekyll, it should be rendered OK. Or you could use a different extension, e.g. `.markdown` to keep it outside the Urubu build (but it will be copied.) Or you could add it to the `ignore_patterns` list in `_site.yml` to make Urubu ignore it. See http://urubu.jandecaluwe.com/manual/structure.html#_siteyml.

**Comment by heeckhau** [comment]
I could not get the ignore_patterns to work. But the renaming README.md to README.markdown gives the expected result.

Thanks!

**Comment by jandecaluwe** [comment]
Inddeed, the `ignore_patterns` were not applied to `*.md` files. Fixed that in development.
