### ISSUE TITLE
Checking for Anchors

### ISSUE THREAD

**Issue by philippefaes** [jandecaluwe/urubu#30]
Hi,
We want to make use of anchors and reference links. http://urubu.jandecaluwe.com/manual/authoring.html#reference-links

It is great that Urubu supports and checks global references, but that seems to fail when using anchors.
In other words, we can link to `[here#subsection]` but if the subsection does not (or no longer) exist, we're in trouble, because the link will open the correct page, but won't jump to the right section.

Am I missing anything? How could we build a safeguard for this?

**Comment by jandecaluwe** [comment]
It is a limitation currently. Urubu obviously know about pages (that is one of the points behind the project) but not about anchors within pages. It would be necessary to extract/use structure from the page, much like for the  `toc`. I haven't yet looked into this, but perhaps I should create a `help wanted` task or so for it.

**Comment by philippefaes** [comment]
Good. I'd be interested. Certainly interested in having this feature. Perhaps interested in helping out if you can give some pointers.

**Comment by jandecaluwe** [comment]
I am working on this. I will start up a test strategy on this occasion.

**Comment by jandecaluwe** [comment]
Solved in release 0.8 (by generating a warning like for pages).

**Comment by alex7217** [comment]
Thank you!
