### ISSUE TITLE
Subfolders without index.md result in weird error messages.

### ISSUE THREAD

**Issue by wallclimber21** [jandecaluwe/urubu#35]
Repro:
In urubu-quickstart root:
- `mkdir my_multipage_article`
- `cp content.md my_multipage_article/1.md`
- `urubu build`

Gives the following error:

    Traceback (most recent call last):
      File "/usr/local/bin/urubu", line 9, in <module>
        load_entry_point('urubu==1.0.0', 'console_scripts', 'urubu')()
      File "/usr/local/lib/python2.7/site-packages/urubu/main.py", line 52, in main
        project.build()
      File "/usr/local/lib/python2.7/site-packages/urubu/project.py", line 475, in build
        proj.make_breadcrumbs()
      File "/usr/local/lib/python2.7/site-packages/urubu/project.py", line 353, in make_breadcrumbs
        breadcrumbs.append(self.site['reflinks'][id])
    KeyError: u'/my_multipage_article'

When the file 1.md is in the project root, there are no issues.

**Comment by wallclimber21** [comment]
Hmm. It actually goes quite a bit deeper, and it's not only with number in the folders.

Example:
* `mkdir test`
* `cp content.md test/c.md`
* `urubu build`

Same error:

        breadcrumbs.append(self.site['reflinks'][id])
    KeyError: u'/test' 

I'm obviously missing fundamental about subfolders, but I can't figure out what it is.

My goal is to use one subfolder for a multi-page article, with assets as well.

**Comment by wallclimber21** [comment]
Turns out that I need to have an index.md in each subfolder.

Still would be nice to have a better error message.

**Comment by jandecaluwe** [comment]
Yes. I implicitly assumed that a folder with Markdown content pages should have an index file that defines their ordering. In that case, I agree that there should be an explicit error when it is missing.

Bu I wonder whether it can perhaps be useful to put some content pages in a folder (e.g. to be used in other pages) that is not intended to be part of the web site itself. In that case, this case should be allowed and breadcrumbs or other website related stuff should not be generated. Two possibilities still: do this silently, or generate a warning that there is no index file.

**Comment by xHN35RQ** [comment]
Perhaps this folder can be a single location that Urubu is aware of and checks for content on every build? And content is only used from this location when referenced by a publicly visible page?

**Comment by jandecaluwe** [comment]
I will go for the explicit error and require an index file in folders with content. This should the common case.

If you don't want the index file to be in the build, you can give it a `null` layout, just like for regular pages.

**Comment by xHN35RQ** [comment]
That makes sense.
