### ISSUE TITLE
Search disabled by md file with an integer as title.

### ISSUE THREAD

**Issue by BertRaeymaekers** [jandecaluwe/urubu#41]
**Trigger**: When you give a markdown file a title that is an integer (e.g. title: 2016).
**Result**: Search stops working.

The fact that search stops working is because in a tipuesearch_content.json this results in:

> "title": 2016, 

When you add quotes manually the search works again:

> "title": "2016",

**Comment by BertRaeymaekers** [comment]
Update on the cause and a possible solution after some looking through the code:
The yaml parser infers the type and makes it into an integer. Solutions are:
 - Workaround in the md: surround the integer with single quotes (e.g. '2016')
 - Title and probably some other things should always be strings. So a fix in Urubu would be to make sure these things are always strings, converting if necessary.

**Comment by jandecaluwe** [comment]
I have added a fix and quickly tested in in development. Please confirm.

**Comment by 42sol-eu** [comment]
I ran a small test 
- change a working inforation.md title in the frontmatter to 2016
- run urubu build and urubu server
- opened the site via localhost:8000
- searched for 2016
- RESULT both the parent page and the information.html were listed in the search ...

**issue should be closed**
Felix
