### ISSUE TITLE
Make Google Analytics ID configurable in site.yml

### ISSUE THREAD

**Issue by philippefaes** [jandecaluwe/urubu#54]
The Google Analytics ID is currently stored in an html file in the _layout folder. It would be more appropriate to strore this information in the _site.yml file. That way, the entire _layout folder can be reused over several sites without modifications. The parameter could be called `google_analytics`.

This does not require a change to Urubu itself. Instead I would like to propose a patch to urubu-quickstart. Would you welcome such a patch?

**Comment by jandecaluwe** [comment]
Sure ;-)

**Comment by philippefaes** [comment]
Created pull request on urubu-quickstart.
