### ISSUE TITLE
Undefined reference:

### ISSUE THREAD

**Issue by bretonio** [jandecaluwe/urubu#57]
May I ask a naive question? In the root of my project alongside the `more`  dropdown menu I have created a new folder with an `index.md` as follows:

```
---
title: Engenhos A-M
layout: index
dropdown: true
content:
    - acrylamid
    - brunch
    - cactus
    - docpad
    - engineer
    - grow
    - hugo
    - hexo
    - jekyll
    - jigsaw
    - lektor
    - middleman
---

```

As you can see, these are examples of static site generators. Each will have a manual page à la `middleman.md` with a briefing and basic rundown on the project in Brazilian Portuguese. There will be a Engenhos N-Z folder as well, of course.

Now when I go to `urubu build` and debug I receive the message `undefined reference: acrylamid` 

Oh, but wait, wait. 

You know what it was? 

**A reference id is not assigned to markdown files without front matter**. 

[Bonks forehead] ...

I ported this project over from attempts to make `material-docs` in Hugo and Mkdocs work for my needs. `Previous` and `next` navigation for example. Do not need it in the navbar, where I want to create several dropdowns.

**Comment by leouieda** [comment]
Hi @bretonio, I don't understand what the issue is about. Were you able to solve the problem? The front matter is required to set basic parameters of the page (title, date, template, etc).

**Comment by bretonio** [comment]
Hi, yes,  I answered my own question in the process of formulating it,
thank you.

**Comment by leouieda** [comment]
👍
