### ISSUE TITLE
two index pages in directory

### ISSUE THREAD

**Issue by ristkof** [jandecaluwe/urubu#59]
If I have a folder with an index.md file that has content sorted on date, and I want another index file, say index-january.md, that includes all my posts from january (and thus a predefined content), this index-january.md file will be included in the index.md content.

What is a way to work around this?

**Comment by 42sol-eu** [comment]
I would solve this with tags. define tags for years and months like 2016 and 2016-01 - so the processor will generate the overviews for you.

there might be a way with intelligent templates too.
