### ISSUE TITLE
Links to Uppercase tag pages are broken

### ISSUE THREAD

**Issue by heeckhau** [jandecaluwe/urubu#68]
If you have tags with upper case characters, links to the corresponding tag pages are incorrectly converted to lower case.

```md
tags :
  - lower
  - UPPER
---
[Links to lower case tags work fine][/tag/lower]
[Links to UPPER case tags fail][/tag/UPPER]
```
The `[/tag/UPPER]` get converted to `<a href="/tag/upper/" title="UPPER">Links to UPPER case tags fail</a>`.

**Comment by bartbrosens** [comment]
This should be resolved by #73
