### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Leon0824** [jandecaluwe/urubu#76]
So many open issues and stop release since 2016

**Comment by LorenzoAncora** [comment]
@Leon0824 
http://urubu.jandecaluwe.com/ is online and many users (like me) still use this software.
This project is not dead. :-)

**Comment by alex7217** [comment]
This is good software -- not dead!

**Comment by elsungen-de** [comment]
I think the issues are many feature requests urubu is great to use.
I switched to lektor which is a complete new way of cms ...
