### ISSUE TITLE
urubu.jandecaluwe.com still announcing 1.3.0 of 2016 as the latest release

### ISSUE THREAD

**Issue by hartwork** [jandecaluwe/urubu#78]
Thought you might want to know :)

Best, Sebastian

**Comment by LorenzoAncora** [comment]
> urubu.jandecaluwe.com still announcing 1.3.0 of 2016 as the latest release

@jandecaluwe `doc/news/2018-08-15.md` is missing and then the home automatically shows the old release.
It would also be a good idea to include the changelog in the commit descriptions when you update the version number (a Git user who sees a commit that has only a version number as its title expects to find details about that version number in the commit comments).

**Comment by LorenzoAncora** [comment]
@jandecaluwe I think this issue is now solved and could be marked as such.
